import "./Home.cy";
import "./Indicators.cy";
import "./Navbar.cy";
import "./Login.cy";
import "./Register.cy";
import "./Quote.cy";
import "./Ratio.cy";
import "./Calculator.cy";
import "./Ideas.cy";
