###
GET http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

###
DELETE http://localhost:3001/api/users/ HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
  "username": "Jonassa", 
  "password": "1234567a",
  "repeatedPassword": "1234567a"
}


###
POST http://localhost:3001/api/login HTTP/1.1
Content-Type: application/json

{
  "username": "Mike", 
  "password": "123"
}



